name: Linux

on:
  push:
    branches: [main]
    tags: ['[0-9]+.[0-9]+.[0-9]+']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          parent-nim-install-directory: $HOME
          nim-install-directory: nim-toolchain

      - name: Run tests
        run: nimble test
        timeout-minutes: 15
